version: '3.8'

services:
  ai-agent:
    build: .
    container_name: northwind-ai-agent
    environment:
      - OPENAI_API_KEY=\
      - DATABASE_PATH=/app/data/northwind.db
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
